REPLACE INTO `dwz_verbaende` VALUES ("100","1","000","Badischer Schachverband");
REPLACE INTO `dwz_verbaende` VALUES ("101","1","100","Mannheim");
REPLACE INTO `dwz_verbaende` VALUES ("102","1","100","Heidelberg");
REPLACE INTO `dwz_verbaende` VALUES ("103","1","100","Odenwald");
REPLACE INTO `dwz_verbaende` VALUES ("104","1","100","Karlsruhe");
REPLACE INTO `dwz_verbaende` VALUES ("105","1","100","Pforzheim");
REPLACE INTO `dwz_verbaende` VALUES ("106","1","100","Mittelbaden");
REPLACE INTO `dwz_verbaende` VALUES ("107","1","100","Ortenau");
REPLACE INTO `dwz_verbaende` VALUES ("108","1","100","Freiburg");
REPLACE INTO `dwz_verbaende` VALUES ("109","1","100","Hochrhein");
REPLACE INTO `dwz_verbaende` VALUES ("10A","1","100","Schwarzwald");
REPLACE INTO `dwz_verbaende` VALUES ("10B","1","100","Bodensee");
REPLACE INTO `dwz_verbaende` VALUES ("200","2","000","Bayerischer Schachbund e.V.");
REPLACE INTO `dwz_verbaende` VALUES ("210","2","200","Mittelfranken");
REPLACE INTO `dwz_verbaende` VALUES ("211","2","210","Mittelfranken-Mitte");
REPLACE INTO `dwz_verbaende` VALUES ("212","2","210","Mittelfranken-Nord");
REPLACE INTO `dwz_verbaende` VALUES ("213","2","210","Mittelfranken-Ost");
REPLACE INTO `dwz_verbaende` VALUES ("214","2","210","Mittelfranken-Süd");
REPLACE INTO `dwz_verbaende` VALUES ("215","2","210","Mittelfranken-West");
REPLACE INTO `dwz_verbaende` VALUES ("220","2","200","München");
REPLACE INTO `dwz_verbaende` VALUES ("230","2","200","Niederbayern");
REPLACE INTO `dwz_verbaende` VALUES ("240","2","200","BV Oberbayern e.V.");
REPLACE INTO `dwz_verbaende` VALUES ("241","2","240","Schachkreis IN-FS");
REPLACE INTO `dwz_verbaende` VALUES ("242","2","240","Schachkreis Inn-Chiemgau");
REPLACE INTO `dwz_verbaende` VALUES ("244","2","240","Schachkreis Zugspitze");
REPLACE INTO `dwz_verbaende` VALUES ("250","2","200","BV Oberfranken");
REPLACE INTO `dwz_verbaende` VALUES ("251","2","250","Kreisverband Bamberg");
REPLACE INTO `dwz_verbaende` VALUES ("252","2","250","Kreisverband Bayreuth");
REPLACE INTO `dwz_verbaende` VALUES ("253","2","250","Kreisverband Hof");
REPLACE INTO `dwz_verbaende` VALUES ("254","2","250","Kreisverband Coburg/Neustadt");
REPLACE INTO `dwz_verbaende` VALUES ("255","2","250","Kreisverband Marktredwitz");
REPLACE INTO `dwz_verbaende` VALUES ("256","2","250","Kreisverband Lichtenfels/Kronach");
REPLACE INTO `dwz_verbaende` VALUES ("260","2","200","Schachverband Oberpfalz e.V.");
REPLACE INTO `dwz_verbaende` VALUES ("270","2","200","Schwaben");
REPLACE INTO `dwz_verbaende` VALUES ("271","2","270"," Augsburg");
REPLACE INTO `dwz_verbaende` VALUES ("272","2","270","Mittelschwaben");
REPLACE INTO `dwz_verbaende` VALUES ("273","2","270","Nordschwaben");
REPLACE INTO `dwz_verbaende` VALUES ("274","2","270","Südschwaben");
REPLACE INTO `dwz_verbaende` VALUES ("280","2","200","Unterfranken e.V");
REPLACE INTO `dwz_verbaende` VALUES ("281","2","280","Spessart/Untermain");
REPLACE INTO `dwz_verbaende` VALUES ("282","2","280","Mainspessart");
REPLACE INTO `dwz_verbaende` VALUES ("283","2","280","Haßberge-Rhön");
REPLACE INTO `dwz_verbaende` VALUES ("284","2","280","Maindreieck");
REPLACE INTO `dwz_verbaende` VALUES ("300","3","000","Berliner Schachverband");
REPLACE INTO `dwz_verbaende` VALUES ("400","4","000","Hamburger Schachverband");
REPLACE INTO `dwz_verbaende` VALUES ("500","5","000","Hessischer Schachverband");
REPLACE INTO `dwz_verbaende` VALUES ("510","5","500","Kassel-Nordhessen");
REPLACE INTO `dwz_verbaende` VALUES ("520","5","500","Osthessen");
REPLACE INTO `dwz_verbaende` VALUES ("530","5","500","Lahn-Eder");
REPLACE INTO `dwz_verbaende` VALUES ("540","5","500","Main-Vogelsberg");
REPLACE INTO `dwz_verbaende` VALUES ("550","5","500","Frankfurt");
REPLACE INTO `dwz_verbaende` VALUES ("560","5","500","Starkenburg");
REPLACE INTO `dwz_verbaende` VALUES ("570","5","500","Main-Taunus");
REPLACE INTO `dwz_verbaende` VALUES ("580","5","500","Rhein-Taunus");
REPLACE INTO `dwz_verbaende` VALUES ("590","5","500","Lahn");
REPLACE INTO `dwz_verbaende` VALUES ("5A0","5","500","Bergstraße");
REPLACE INTO `dwz_verbaende` VALUES ("600","6","000","Schachbund Nordrhein-Westfalen e.V.");
REPLACE INTO `dwz_verbaende` VALUES ("610","6","600","SV Ruhrgebiet e.V.");
REPLACE INTO `dwz_verbaende` VALUES ("611","6","610","Schachbezirk Bochum");
REPLACE INTO `dwz_verbaende` VALUES ("612","6","610","Schachgemeinschaft Dortmund");
REPLACE INTO `dwz_verbaende` VALUES ("613","6","610","Schachbezirk Essen");
REPLACE INTO `dwz_verbaende` VALUES ("614","6","610","Schachbezirk Emscher-Lippe");
REPLACE INTO `dwz_verbaende` VALUES ("615","6","610","Schachbezirk Hamm");
REPLACE INTO `dwz_verbaende` VALUES ("616","6","610","Mülheim an der Ruhr 1922 e.V.");
REPLACE INTO `dwz_verbaende` VALUES ("617","6","610","Schachbezirk Herne - Vest");
REPLACE INTO `dwz_verbaende` VALUES ("620","6","600","Niederrheinischer Schachverband 1901 e.V.");
REPLACE INTO `dwz_verbaende` VALUES ("621","6","620","Schachbezirk Bergisch-Land");
REPLACE INTO `dwz_verbaende` VALUES ("622","6","620","Schachbezirk Düsseldorf");
REPLACE INTO `dwz_verbaende` VALUES ("623","6","620","Schachbezirk Duisburg");
REPLACE INTO `dwz_verbaende` VALUES ("624","6","620","Linker Niederrhein");
REPLACE INTO `dwz_verbaende` VALUES ("625","6","620","Schachbezirk Kreis Wesel e.V.");
REPLACE INTO `dwz_verbaende` VALUES ("630","6","600","Schachverband Südwestfalen");
REPLACE INTO `dwz_verbaende` VALUES ("632","6","630","Schachbezirk Iserlohn");
REPLACE INTO `dwz_verbaende` VALUES ("633","6","630","Schachbezirk Oberberg");
REPLACE INTO `dwz_verbaende` VALUES ("634","6","630","Schachbezirk Hochsauerland");
REPLACE INTO `dwz_verbaende` VALUES ("635","6","630","Schachbezirk Sauerland");
REPLACE INTO `dwz_verbaende` VALUES ("636","6","630","Schachbezirk Siegerland");
REPLACE INTO `dwz_verbaende` VALUES ("640","6","600","Schachverband Ostwestfalen-Lippe");
REPLACE INTO `dwz_verbaende` VALUES ("641","6","640","Schachbezirk Bielefeld");
REPLACE INTO `dwz_verbaende` VALUES ("642","6","640","Schachbezirk Hellweg");
REPLACE INTO `dwz_verbaende` VALUES ("643","6","640","Schachbezirk Lippe");
REPLACE INTO `dwz_verbaende` VALUES ("644","6","640","Schachbezirk Porta");
REPLACE INTO `dwz_verbaende` VALUES ("645","6","640","Schachbezirk Teutoburger Wald-West");
REPLACE INTO `dwz_verbaende` VALUES ("650","6","600","Schachverband Münsterland");
REPLACE INTO `dwz_verbaende` VALUES ("651","6","650","Schachbezirk Steinfurt");
REPLACE INTO `dwz_verbaende` VALUES ("652","6","650","Schachbezirk Borken");
REPLACE INTO `dwz_verbaende` VALUES ("653","6","650","Schachbezirk Münster");
REPLACE INTO `dwz_verbaende` VALUES ("660","6","600","Schachverband Mittelrhein e.V.");
REPLACE INTO `dwz_verbaende` VALUES ("661","6","660","Aachener Schachverband 1928 e.V.");
REPLACE INTO `dwz_verbaende` VALUES ("662","6","660","Bonn/Rhein-Sieg e.V.");
REPLACE INTO `dwz_verbaende` VALUES ("663","6","660","Kölner Schachverband von 1920 e.V.");
REPLACE INTO `dwz_verbaende` VALUES ("664","6","660","Schachbezirk Rur-Erft");
REPLACE INTO `dwz_verbaende` VALUES ("665","6","660","Schachbezirk Rhein-Wupper");
REPLACE INTO `dwz_verbaende` VALUES ("700","7","000","Niedersächsischer Schachverband e. V.");
REPLACE INTO `dwz_verbaende` VALUES ("701","7","700","Bezirk 1 Hannover");
REPLACE INTO `dwz_verbaende` VALUES ("702","7","700","Bezirk 2 Braunschweig");
REPLACE INTO `dwz_verbaende` VALUES ("703","7","700","Bezirk 3 Südniedersachsen");
REPLACE INTO `dwz_verbaende` VALUES ("704","7","700","Bezirk 4 Lüneburg");
REPLACE INTO `dwz_verbaende` VALUES ("705","7","700","Bezirk 5 Oldenburg-Ostfriesland");
REPLACE INTO `dwz_verbaende` VALUES ("706","7","700","Bezirk 6 Osnabrück-Emsland");
REPLACE INTO `dwz_verbaende` VALUES ("800","8","000","SB Rheinland-Pfalz e.V.");
REPLACE INTO `dwz_verbaende` VALUES ("810","8","800","Schachverband Rheinland e.V.");
REPLACE INTO `dwz_verbaende` VALUES ("811","8","810","Bezirk I Rhein-Ahr-Mosel");
REPLACE INTO `dwz_verbaende` VALUES ("812","8","810","Bezirk II Rhein-Nahe");
REPLACE INTO `dwz_verbaende` VALUES ("813","8","810","Bezirk III Rhein-Westerwald");
REPLACE INTO `dwz_verbaende` VALUES ("815","8","810","Bezirk IV Trier");
REPLACE INTO `dwz_verbaende` VALUES ("820","8","800","SB Rheinhessen e.V.");
REPLACE INTO `dwz_verbaende` VALUES ("830","8","800","Pfälzischer Schachbund e.V.");
REPLACE INTO `dwz_verbaende` VALUES ("831","8","830","Bezirk I Kaiserslautern");
REPLACE INTO `dwz_verbaende` VALUES ("832","8","830","Bezirk II Ludwigshafen");
REPLACE INTO `dwz_verbaende` VALUES ("833","8","830","Bezirk III Neustadt");
REPLACE INTO `dwz_verbaende` VALUES ("834","8","830","Bezirk IV Landau");
REPLACE INTO `dwz_verbaende` VALUES ("835","8","830","Bezirk V Pirmasens");
REPLACE INTO `dwz_verbaende` VALUES ("836","8","830","Bezirk VI Ramstein");
REPLACE INTO `dwz_verbaende` VALUES ("900","9","000","Saarländischer Schachverband");
REPLACE INTO `dwz_verbaende` VALUES ("A00","A","000","SVB Schleswig-Holstein");
REPLACE INTO `dwz_verbaende` VALUES ("A01","A","A00","Bezirk I Nord");
REPLACE INTO `dwz_verbaende` VALUES ("A02","A","A00","Bezirk II West");
REPLACE INTO `dwz_verbaende` VALUES ("A06","A","A00","Bezirk VI Kiel");
REPLACE INTO `dwz_verbaende` VALUES ("A08","A","A00","Bezirk Ost");
REPLACE INTO `dwz_verbaende` VALUES ("B00","B","000","Landesschachbund Bremen");
REPLACE INTO `dwz_verbaende` VALUES ("C00","C","000","Schachverband Württemberg e.V.");
REPLACE INTO `dwz_verbaende` VALUES ("C01","C","C00","Bezirk Oberschwaben");
REPLACE INTO `dwz_verbaende` VALUES ("C02","C","C00","Bezirk Alb/Schwarzwald");
REPLACE INTO `dwz_verbaende` VALUES ("C03","C","C00","Bezirk Neckar-Fils");
REPLACE INTO `dwz_verbaende` VALUES ("C04","C","C00","Bezirk Ostalb");
REPLACE INTO `dwz_verbaende` VALUES ("C05","C","C00","Bezirk Stuttgart");
REPLACE INTO `dwz_verbaende` VALUES ("C06","C","C00","Bezirk Unterland-Hohenlohe");
REPLACE INTO `dwz_verbaende` VALUES ("D00","D","000","Schachbund Brandenburg");
REPLACE INTO `dwz_verbaende` VALUES ("D10","D","D00","Cottbus");
REPLACE INTO `dwz_verbaende` VALUES ("D20","D","D00","Frankfurt/O.");
REPLACE INTO `dwz_verbaende` VALUES ("D30","D","D00","Potsdam");
REPLACE INTO `dwz_verbaende` VALUES ("E00","E","000","LSV Mecklenburg-Vorpommern");
REPLACE INTO `dwz_verbaende` VALUES ("E01","E","E00","Spielbezirk West");
REPLACE INTO `dwz_verbaende` VALUES ("E02","E","E00","Spielbezirk Mitte");
REPLACE INTO `dwz_verbaende` VALUES ("E03","E","E00","Spielbezirk Ost");
REPLACE INTO `dwz_verbaende` VALUES ("F00","F","000","Schachverband Sachsen e.V.");
REPLACE INTO `dwz_verbaende` VALUES ("F10","F","F00","Leipzig");
REPLACE INTO `dwz_verbaende` VALUES ("F11","F","F10","Landkreis Delitzsch");
REPLACE INTO `dwz_verbaende` VALUES ("F12","F","F10","Landkreis Döbeln");
REPLACE INTO `dwz_verbaende` VALUES ("F13","F","F10","Landkreis Torgau-Oschatz");
REPLACE INTO `dwz_verbaende` VALUES ("F15","F","F10","Stadt Leipzig");
REPLACE INTO `dwz_verbaende` VALUES ("F18","F","F10","Kreis Leipziger Land");
REPLACE INTO `dwz_verbaende` VALUES ("F19","F","F10","Muldentalkreis");
REPLACE INTO `dwz_verbaende` VALUES ("F20","F","F00","Dresden");
REPLACE INTO `dwz_verbaende` VALUES ("F21","F","F20","Landkreis Riesa-Großenhain");
REPLACE INTO `dwz_verbaende` VALUES ("F22","F","F20","Landkreis Sächsische Schweiz");
REPLACE INTO `dwz_verbaende` VALUES ("F23","F","F20","Landkreis Kamenz");
REPLACE INTO `dwz_verbaende` VALUES ("F24","F","F20","Stadt Hoyerswerda");
REPLACE INTO `dwz_verbaende` VALUES ("F25","F","F20","Weiseritzkreis");
REPLACE INTO `dwz_verbaende` VALUES ("F26","F","F20","Landkreis Meißen");
REPLACE INTO `dwz_verbaende` VALUES ("F27","F","F20","Stadt Görlitz");
REPLACE INTO `dwz_verbaende` VALUES ("F28","F","F20","Stadt Dresden");
REPLACE INTO `dwz_verbaende` VALUES ("F29","F","F20","Landkreis Löbau-Zittau");
REPLACE INTO `dwz_verbaende` VALUES ("F2A","F","F20","Landkreis Bautzen");
REPLACE INTO `dwz_verbaende` VALUES ("F2B","F","F20","Niederschlesischer Oberlausitzkreis");
REPLACE INTO `dwz_verbaende` VALUES ("F30","F","F00","Chemnitz");
REPLACE INTO `dwz_verbaende` VALUES ("F31","F","F30","Landkreis Stollberg");
REPLACE INTO `dwz_verbaende` VALUES ("F32","F","F30","Landkreis Mittweida");
REPLACE INTO `dwz_verbaende` VALUES ("F33","F","F30","Landkreis Freiberg");
REPLACE INTO `dwz_verbaende` VALUES ("F34","F","F30","Landkreis Chemnitzer Land");
REPLACE INTO `dwz_verbaende` VALUES ("F35","F","F30","Landkreis Annaberg");
REPLACE INTO `dwz_verbaende` VALUES ("F36","F","F30","Stadt Chemnitz");
REPLACE INTO `dwz_verbaende` VALUES ("F37","F","F30","Vogtlandkreis");
REPLACE INTO `dwz_verbaende` VALUES ("F38","F","F30","Stadt Zwickau");
REPLACE INTO `dwz_verbaende` VALUES ("F39","F","F30","Mittlerer Erzgebirgskreis");
REPLACE INTO `dwz_verbaende` VALUES ("F3A","F","F30","Landkreis Zwicker Land");
REPLACE INTO `dwz_verbaende` VALUES ("F3B","F","F30","Stadt Plauen");
REPLACE INTO `dwz_verbaende` VALUES ("F3C","F","F30","Landkreis Aue-Schwarzenberg");
REPLACE INTO `dwz_verbaende` VALUES ("G00","G","000","LSV Sachsen-Anhalt");
REPLACE INTO `dwz_verbaende` VALUES ("G01","G","G00","Schachbezirk Dessau");
REPLACE INTO `dwz_verbaende` VALUES ("G02","G","G00","Schachbezirk Halle");
REPLACE INTO `dwz_verbaende` VALUES ("G03","G","G00","Schachbezirk Magdeburg");
REPLACE INTO `dwz_verbaende` VALUES ("H00","H","000","Thüringer Schachbund");
REPLACE INTO `dwz_verbaende` VALUES ("H10","H","H00","Schachbezirk Nord");
REPLACE INTO `dwz_verbaende` VALUES ("H11","H","H10","Schachkreis Kyffhäuser");
REPLACE INTO `dwz_verbaende` VALUES ("H12","H","H10","Schachkreis Eichsfeld");
REPLACE INTO `dwz_verbaende` VALUES ("H13","H","H10","Schachkreis Nordhausen");
REPLACE INTO `dwz_verbaende` VALUES ("H14","H","H10","Schachkreis Unstrut-Hainich");
REPLACE INTO `dwz_verbaende` VALUES ("H15","H","H10","Schachkreis Gotha");
REPLACE INTO `dwz_verbaende` VALUES ("H20","H","H00","Schachbezirk Mitte");
REPLACE INTO `dwz_verbaende` VALUES ("H21","H","H20","Schachkreis Erfurt");
REPLACE INTO `dwz_verbaende` VALUES ("H22","H","H20","Schachkreis Weimarer Land");
REPLACE INTO `dwz_verbaende` VALUES ("H23","H","H20","Schachkreis Sömmerda");
REPLACE INTO `dwz_verbaende` VALUES ("H24","H","H20","Schachkreis Ilm-Kreis");
REPLACE INTO `dwz_verbaende` VALUES ("H25","H","H20","Schachkreis Weimar");
REPLACE INTO `dwz_verbaende` VALUES ("H30","H","H00","Schachbezirk Ost");
REPLACE INTO `dwz_verbaende` VALUES ("H31","H","H30","Schachkreis Gera");
REPLACE INTO `dwz_verbaende` VALUES ("H32","H","H30","Schachkreis Jena/Holzlandkreis");
REPLACE INTO `dwz_verbaende` VALUES ("H33","H","H30","Schachkreis Greiz");
REPLACE INTO `dwz_verbaende` VALUES ("H34","H","H30","Schachkreis Altenburger Land");
REPLACE INTO `dwz_verbaende` VALUES ("H35","H","H30","Schachkreis Saalfeld-Rudolstadt/SOK");
REPLACE INTO `dwz_verbaende` VALUES ("H40","H","H00","Schachbezirk Süd");
REPLACE INTO `dwz_verbaende` VALUES ("H41","H","H40","Schachkreis Schmalkalden-Meiningen/Suhl");
REPLACE INTO `dwz_verbaende` VALUES ("H42","H","H40","Schachkreis Sonneberg/Hildburghausen");
REPLACE INTO `dwz_verbaende` VALUES ("H43","H","H40","Schachkreis Wartburgkreis/Eisenach");
REPLACE INTO `dwz_verbaende` VALUES ("L00","L","000","Deutscher Blinden- und Sehbehinderten-Schachbund");
REPLACE INTO `dwz_verbaende` VALUES ("M00","M","000","Schwalbe");
